name: Build ShaderToggler (fixed paths, x86 & x64)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, Win32]

    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Locate project
        id: findproj
        shell: pwsh
        run: |
          $cands = Get-ChildItem -Recurse -Filter *.vcxproj | Select-Object -Expand FullName
          if (-not $cands) { Write-Error "No .vcxproj found"; exit 1 }
          $proj = $cands | Where-Object { $_ -like "*ShaderToggler.vcxproj" } | Select-Object -First 1
          if (-not $proj) { $proj = $cands | Select-Object -First 1 }
          echo "PROJ=$proj" >> $env:GITHUB_OUTPUT
          Write-Host "Using project: $proj"

      - name: Build ${{ matrix.platform }} Release
        run: >
          msbuild "${{ steps.findproj.outputs.PROJ }}"
          /p:Configuration=Release
          /p:Platform=${{ matrix.platform }}

      - name: Package .addon (handle both output layouts)
        shell: pwsh
        run: |
          $plat = "${{ matrix.platform }}"
          $root = Split-Path "${{ steps.findproj.outputs.PROJ }}"

          # Candidate output dirs we saw in your logs
          $cand = @(
            Join-Path $root "ShaderToggler\$plat\Release"
            Join-Path $root "$plat\Release"
          )

          $found = $false
          foreach ($dir in $cand) {
            if (Test-Path $dir) {
              Write-Host "Checking $dir"
              $dll = Join-Path $dir "ShaderToggler.dll"
              $addon = Join-Path $dir "ShaderToggler.addon"
              if (Test-Path $dll) {
                Copy-Item $dll $addon -Force
                Write-Host "Created .addon next to DLL in $dir"
                $found = $true
              } elseif (Test-Path $addon) {
                Write-Host "Found existing .addon in $dir"
                $found = $true
              }
            }
          }

          if (-not $found) {
            Write-Host "No DLL/ADDON found in candidate dirs. Listing contents:"
            $cand | ForEach-Object { if (Test-Path $_) { Get-ChildItem -Recurse $_ | Select-Object FullName } }
            Write-Error "ShaderToggler output not found. Did the build fail earlier?"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShaderToggler-${{ matrix.platform }}-Release
          path: |
            **/src/ShaderToggler/${{ matrix.platform }}/Release/ShaderToggler.dll
            **/src/ShaderToggler/${{ matrix.platform }}/Release/ShaderToggler.addon
            **/src/${{ matrix.platform }}/Release/ShaderToggler.dll
            **/src/${{ matrix.platform }}/Release/ShaderToggler.addon
