name: Build ShaderToggler (x86 & x64)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, Win32]
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -S . -B build/${{ matrix.arch }} -A ${{ matrix.arch }}
      - name: Build
        run: cmake --build build/${{ matrix.arch }} --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShaderToggler-${{ matrix.arch }}-Release
          path: |
            build/${{ matrix.arch }}/Release/ShaderToggler.dll
            build/${{ matrix.arch }}/Release/ShaderToggler.addon
