name: build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build x64 Release
        run: msbuild src/ShaderToggler.vcxproj /p:Configuration=Release /p:Platform=x64 /m

      - name: Build Win32 Release
        run: msbuild src/ShaderToggler.vcxproj /p:Configuration=Release /p:Platform=Win32 /m

      - name: Package artifacts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $roots = @(
            'src\x64\Release',
            'src\Release',
            'src\ShaderToggler\x64\Release',     # older proj layouts
            'src\ShaderToggler\Release'
          )

          New-Item -ItemType Directory -Force -Path out | Out-Null

          foreach ($r in $roots) {
            if (Test-Path $r) {
              Get-ChildItem $r -File | Write-Host
            }
          }

          # Collect x64
          $x64 = Get-ChildItem -Recurse -Path src -Include *.addon64,*.pdb -File | Where-Object { $_.FullName -match 'x64\\Release' }
          if (-not $x64) { throw "x64 artifacts not found" }
          New-Item -ItemType Directory -Force -Path out\x64 | Out-Null
          $x64 | Copy-Item -Destination out\x64 -Force

          # Collect Win32
          $x86 = Get-ChildItem -Recurse -Path src -Include *.addon,*.pdb -File | Where-Object { $_.FullName -match 'Release(\\|$)' -and $_.Extension -in '.addon','.pdb' }
          if (-not $x86) { throw "Win32 artifacts not found" }
          New-Item -ItemType Directory -Force -Path out\Win32 | Out-Null
          $x86 | Copy-Item -Destination out\Win32 -Force

          # Optional: include README, LICENSE, INI template, etc.
          if (Test-Path README.md) { Copy-Item README.md out -Force }
          if (Test-Path LICENSE)   { Copy-Item LICENSE out -Force }

          Compress-Archive -Path out\* -DestinationPath ShaderToggler_Package.zip -Force

      - name: Upload build artifacts (raw)
        uses: actions/upload-artifact@v4
        with:
          name: ShaderToggler_raw
          path: out/**

      - name: Upload release zip
        uses: actions/upload-artifact@v4
        with:
          name: ShaderToggler_zip
          path: ShaderToggler_Package.zip
            **/*.binlog
            **/Release/**
