name: Build & Package ShaderToggler

on:
  workflow_dispatch:
  push:
    paths:
      - 'ShaderToggler-1.2.1_src/**'
      - '.github/workflows/package.yml'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, Win32]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Build to a known location so packaging is simple
      - name: Build ${{ matrix.platform }} Release
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Recurse -Filter ShaderToggler.vcxproj | Select-Object -First 1 -Expand FullName
          if (-not $proj) { throw "ShaderToggler.vcxproj not found" }
          $out = Join-Path (Get-Location) ("out\" + "${{ matrix.platform }}" + "\Release\")
          New-Item -ItemType Directory -Force -Path $out | Out-Null
          msbuild $proj /p:Configuration=Release /p:Platform=${{ matrix.platform }} /p:OutDir="$out" /m /v:m
          Write-Host "Built to $out"
          Get-ChildItem $out

      - name: Make .addon (from newest .dll)
        shell: pwsh
        run: |
          $out = Join-Path (Get-Location) ("out\" + "${{ matrix.platform }}" + "\Release\")
          $dll = Get-ChildItem -Path $out -Filter *.dll -File | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $dll) { throw "No DLL produced for ${{ matrix.platform }}" }
          Copy-Item $dll.FullName (Join-Path $out "ShaderToggler.addon") -Force
          Get-ChildItem $out

      - name: Upload per-platform artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: |
            out/${{ matrix.platform }}/Release/*.dll
            out/${{ matrix.platform }}/Release/*.addon

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download x64
        uses: actions/download-artifact@v4
        with:
          name: build-x64
          path: pkg/x64

      - name: Download Win32
        uses: actions/download-artifact@v4
        with:
          name: build-Win32
          path: pkg/Win32

      - name: Add sources to package
        run: |
          mkdir -p pkg/ShaderToggler-1.2.1_src
          cp -R ShaderToggler-1.2.1_src/* pkg/ShaderToggler-1.2.1_src/ || true

      - name: Make single ZIP
        run: |
          cd pkg
          zip -r ../ShaderToggler-Package.zip .

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: ShaderToggler-Package
          path: ShaderToggler-Package.zip
