name: Build ShaderToggler Advanced 1.3.0-Gametism

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, Win32]

    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Locate project
        id: findproj
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Recurse -Filter ShaderToggler.vcxproj | Select-Object -Expand FullName -First 1
          if (-not $proj) { Write-Error "ShaderToggler.vcxproj not found"; exit 1 }
          "PROJ=$proj" >> $env:GITHUB_OUTPUT
          Write-Host "Using project: $proj"

      - name: Build ${{ matrix.platform }} Release (force OutDir)
        shell: pwsh
        run: |
          $plat = "${{ matrix.platform }}"
          $proj = "${{ steps.findproj.outputs.PROJ }}"
          $out = Join-Path (Get-Location) ("out\" + $plat + "\Release\")
          New-Item -ItemType Directory -Force -Path $out | Out-Null
          msbuild $proj /t:Build /p:Configuration=Release /p:Platform=$plat /p:OutDir="$out" /m /v:m
          Write-Host "Contents of $out:"
          Get-ChildItem -Recurse $out

      - name: Package .addon
        shell: pwsh
        run: |
          $plat = "${{ matrix.platform }}"
          $out = Join-Path (Get-Location) ("out\" + $plat + "\Release\")
          $dll = Get-ChildItem -Path $out -Filter *.dll -File | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $dll) { Write-Error "No DLL found in $out"; exit 1 }
          Copy-Item $dll.FullName (Join-Path $out "ShaderToggler.addon") -Force
          Write-Host "Packaged: $(Join-Path $out 'ShaderToggler.addon')"

      - name: Upload per-platform artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ShaderToggler-Advanced-1.3.0-Gametism-Gametism-${{ matrix.platform }}
          path: |
            out/${{ matrix.platform }}/Release/*.dll
            out/${{ matrix.platform }}/Release/*.addon

  bundle:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: ShaderToggler-Advanced-1.3.0-Gametism-*
          merge-multiple: true
      - name: Create release bundle
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          $x64 = Get-ChildItem -Recurse -Filter ShaderToggler.addon | Where-Object { $_.FullName -match "\\x64\\Release\\" } | Select-Object -First 1
          $x86 = Get-ChildItem -Recurse -Filter ShaderToggler.addon | Where-Object { $_.FullName -match "\\Win32\\Release\\" } | Select-Object -First 1
          if ($x64) { Copy-Item $x64.FullName (Join-Path "dist" "ShaderToggler.x64.addon") -Force }
          if ($x86) { Copy-Item $x86.FullName (Join-Path "dist" "ShaderToggler.x86.addon") -Force }
          Copy-Item README.md dist -Force
          Copy-Item LICENSE dist -Force
          Compress-Archive -Path dist\* -DestinationPath ShaderToggler-Advanced-1.3.0-Gametism.zip -Force
      - name: Upload final bundle
        uses: actions/upload-artifact@v4
        with:
          name: ShaderToggler-Advanced-1.3.0-Gametism
          path: ShaderToggler-Advanced-1.3.0-Gametism.zip
